---
title: "Campus"
author: "Crystal Baker"
date: "5/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
train = read.csv('/Users/reshea/Desktop/Datasets for Fun/train.csv')
test = read.csv('/Users/reshea/Desktop/Datasets for Fun/test.csv')
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
```

## Testing
```{r}
test$Survived <- 0
test$Survived[test$Sex == 'female'] <- 1
test$Survived[test$Sex == 'male' & test$Pclass == 1 & test$Pclass == 1] <- 1
```

## To Submit
```{r}
submit <- data.frame(PassengerId = test$PassengerId, Survived = test$Survived)
write.csv(submit, file = "theyallperish.csv", row.names = FALSE)
```

## Training
```{r}
str(train)
table(train$Survived)
prop.table(table(train$Survived))
test$Survived <- rep(0, 418)
submit <- data.frame(PassengerId = test$PassengerId, Survived=test$Survived)
```

## Checking Sex and Age
```{r}
summary(train$Sex)
summary(train$Age)
prop.table(table(train$Sex, train$Survived), 1)
train$Child <- 0
train$Child[train$Age < 18] <- 1
aggregate(Survived ~ Child + Sex + Pclass, data = train, FUN=function(x) { sum(x)/length(x)}) 
```

## Class
```{r}
aggregate(Survived ~ Child + Sex + Pclass, data = train, FUN=function(x) { sum(x)/length(x)})
```
## Decision Tree - 0.78468
```{r}
fit = rpart(Survived ~Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, data = train, method ="class", control=rpart.control(minsplit = 3, cp = .01))
fancyRpartPlot(fit)
prediction <- predict(fit, test, type = "class")
submit <- data.frame(PassengerId = test$PassengerId, Survived=prediction)
write.csv(submit, file = "myfirstdtree.csv", row.names = FALSE)
```

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
